import Header from './Header'
import Menu from './Menu'
import Bread from './Bread'
import Sider from './Sider'
import styles from './Layout.less'
import UseInfoModal from './useInfoModal'
import SpeechcraftModal from './speechcraftModal'
import EditPwdModal from './editPwdModal'
import QuickSearchModal from './quickSearchModal'
import Appointment from './Appointment'
import Calendar from './Calendar'
import Message from './Message'
export { Header, Menu, Bread, Sider, styles ,UseInfoModal,SpeechcraftModal,EditPwdModal,QuickSearchModal,Appointment,Calendar,Message}
